### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by acheam0** [mcpcpc/k1ss#3]
Minification can significantly reduce page size. Dylan did this with `sed ':a;N;$!ba;s|>\s*<|><|g'`, but there is also [this tool](https://github.com/tdewolff/minify), which can do CSS, XML, etc as well.

**Comment by mcpcpc** [comment]
done https://github.com/mcpcpc/k1ss/commit/bcc626e22e0abae8f307ef08f965c2adbe7851aa
